version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.15.5
    container_name: es762
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata: